---
# Use the eos_config module to configure three vlans on all four Arista switches.
# Assign both the vlan id and the vlan name. 

- name: Configure VLANS on Arista
  gather_facts: no
  hosts: arista
  vars:
    creds:
        host: "{{ eapi_hostname }}"
        username: "{{ eapi_username }}"
        password: "{{ eapi_password }}"
  tasks:
    - name: Configure VLANS
      eos_config:
        provider: "{{ creds }}"
        # transport: eapi
        transport: cli
        lines:
          - vlan 240
          - name kb240
          - vlan 241
          - name kb241
          - vlan 242
          - name kb242
        replace: block
        match: line
