---

- name: Test ntc-ansible on IOS (save_config)
  hosts: pynet-rtr1
  gather_facts: False
  tags: cisco
  tasks:
    - ntc_save_config:
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        platform: cisco_ios_ssh
        local_file: "{{ host }}.txt"

- name: Test ntc-ansible on EOS (save_config)
  hosts: pynet-sw1
  gather_facts: False
  tags: arista
  tasks:
    - ntc_save_config:
        host: "{{ eapi_hostname }}"
        username: "{{ eapi_username }}"
        password: "{{ eapi_password }}"
        platform: arista_eos_eapi
        transport: https
        local_file: "{{ eapi_hostname }}.txt"

